server:
    port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring5?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root


logging:
  level:
    com:
      example:
        mapper : debug